export const SET_PLAYS = "SET_PLAYS";
export const SET_GAME_STARTED = "SET_GAME_STARTED";
export const SET_PLAYER_TIME = "SET_PLAYER_TIME";
export const SET_GAME_FINISHED = "SET_GAME_FINISHED";
export const SET_GAME_WINNER = "SET_GAME_WINNER";
